apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluentbit
  namespace: logging
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: fluent-bit
  namespaceSelector:
    matchNames:
      - logging
  endpoints:
    - port: http
      path: /api/v1/metrics/prometheus
      interval: 30s
